#include <regex>
#include <map>
#include <ranges>
#include <utility>
#include <fstream>
#include <sstream>
#include <random>
#include <algorithm>
#include <memory>
#include <math.h>
#include <vector>
#include <numbers>
#include <memory>
#include <iostream>
#include <string>
#include <eigen3/Eigen/Dense>
